-- === Saneamiento de arrays legacy de tags ===
--
-- ATENCIÓN: Esta migración está INTENCIONALMENTE VACÍA.
--
-- El build de Vercel usa `prisma db push` (no `prisma migrate deploy`),
-- por lo que las migraciones SQL personalizadas no se ejecutan en
-- producción. El saneamiento se hace desde el código en runtime,
-- a través del endpoint:
--
--   POST /api/admin/sanitize-professional-tags
--
-- (ver src/app/api/admin/sanitize-professional-tags/route.ts)
--
-- La lógica original (función filter_json_array_to_canonical + UPDATEs)
-- quedó documentada en git history por si en el futuro se migra a
-- `prisma migrate deploy` y se quiere ejecutar como SQL puro.
--
-- No operations to execute.
SELECT 1;
